[package]
name = "innocent_lib"
version = "0.1.0"
authors = ["Eric Leijonmarck <eric.leijonmarck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[lib]
proc-macro = true